Resources:
  DistributionBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ${self:custom.s3.buckets.distribution}
      CorsConfiguration:
        CorsRules: 
        - AllowedHeaders: 
            - 'Content-Length'
          AllowedMethods:
           - GET
          AllowedOrigins: 
            - '*'
          Id: 'compressed-js-rule'
  LogBucket:
    Type: 'AWS::S3::Bucket'
    DependsOn:
      - BucketNotifications
      - BucketNotificationPolicy
    Properties:
      BucketName: ${self:custom.s3.buckets.logs}
      NotificationConfiguration:
        TopicConfigurations: 
          - Event: s3:ObjectCreated:*
            Topic: 
              Ref: BucketNotifications
            Filter: 
              S3Key: 
                Rules: 
                  - Name: prefix
                    Value: '${self:custom.prefixes.incoming}'
